apiVersion: v1
kind: Service
metadata:
  name: complete-pipeline-service
spec:
  selector:
    app: complete-pipeline
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32414
